### ISSUE TITLE
Use the extended set from materialdesignicons.com

### ISSUE THREAD

**Issue by mdemierre** [nathanielw/Material-Icons-for-Pencil#3]
I think it would be great to use the icons provided on http://materialdesignicons.com. They include both the Google icons and community-made ones.

Their github repository is at https://github.com/Templarian/MaterialDesign.

**Comment by nathanielw** [comment]
Thanks for the suggestion, I didn't know about that icon set. 
The set doesn't seem to contains the latest icons from the Google repo (~100 or so were added last month), so I'm not sure if I'd want to switch this over to using it as a base just yet. Looks like there's [some work](https://github.com/Templarian/MaterialDesign/issues/420) on getting them added though, so maybe once that's been completed I'll switch this over. I'll make a branch here for the time being and make a start on changing the generator script.

**Comment by nathanielw** [comment]
I've added a release generated with the extended icon set: [v2.0.0-beta](https://github.com/nathanielw/Material-Icons-for-Pencil/releases/tag/v2.0.0-beta)

Hopefully the missing icons from Google's repo will be added to the set sometime. If not, I I'll probably just switch the master branch over to the extended set after a while anyway, since maintaining two versions could get messy.
